#!/usr/bin/env python
""" tool to scrape lists of trinity mirror newspapers

outputs title+website
"""

import lxml.html
import urllib2
import re


blacklist = [
    'northeastweddingfair.co.uk',
    'www.whatsonne.co.uk',  # covered by chroniclelive.co.uk
    'gmgrd.co.uk',
    'gmggm.co.uk',
    'gotravelholidays.com',
    'go-travelholidays.co.uk',
    'jobsnw.co.uk',
    'love2love.co.uk',
    'menfinancialservices.co.uk',
    'menmortgageservices.com',
    'menmortgageservices.co.uk',
    'menmortgageservices.com',
    'abmedia.co.uk',
    'thejobsmine.co.uk',
    'travelnewspaper.co.uk',
    'urban-life.co.uk',
    'thehomesmine.co.uk',
    'citylife.co.uk',
    ]

def scrape_index(top_url):
    html = urllib2.urlopen(top_url).read()
    doc = lxml.html.fromstring(html)

    for a in doc.cssselect('li.toplevelsite'):
        for foo in a.cssselect('ul'):
            foo.drop_tree()

        txt = a.text_content().strip()
        (title,url) = re.compile(r'\s*-\s+').split(txt)

        crap = False
        for b in blacklist:
            if b in url:
                crap = True
                continue

        if not crap:
            assert ',' not in title
            assert ',' not in url
            print 'http://%s,%s' %(url,title)



def main():
    regionals = "http://www.trinitymirror.com/our-portfolio/regionals/index-of-digital-sites/regionals-index/"
    scrape_index(regionals)

if __name__ == '__main__':
    main()

