#!/usr/bin/env python2.4
#
# Byline dev tool
# Print out all the bylines that won't correctly parse
#

import sys

sys.path.append( "../pylib" )

from JL import DB,Byline,Journo


def main():
	conn = DB.Connect()

	c = conn.cursor()

	c.execute( 'SELECT id,byline,srcorg FROM article' )

	cnt=0
	blankcnt=0
	failcnt=0

	while 1:
		row = c.fetchone()
		if not row:
			break
		cnt=cnt+1

		article_id = row[0]
		byline = row[1].decode( 'utf-8' ).strip()
		if not byline:
			blankcnt = blankcnt + 1
			continue		# blank byline

		details = Byline.CrackByline( byline )

		if details is None:
			print "%s -- FAIL" %(byline)
			failcnt = failcnt + 1
			continue

		foo = ''
		for d in details:
			foo = foo + str(d)

#		print "%s -- %s" % (byline,foo)

	print "Summary:"
	print "%d total" % (cnt)
	print "%d blank (%.2f%%)" % (blankcnt, float(100*blankcnt)/float(cnt) )
	print "%d failed (%.2f%%)" % (failcnt, float(100*failcnt)/float(cnt) )
	
main()

